import ky from "ky";
import { MecchiKV } from "../../../stores/nodes";

const MecchiBarkNodeInfo = {
  type: 'bark',
  title: 'Bark',
  group: 'generate',

  inputs: [{
    name: 'prompt',
    type: 'text',
  }],
  outputs: [{
    name: 'sample',
    type: 'sound',
  }],

  units: [{
    name: "model",
    title: "Model",
    type: "list",
    values: [
      "suno/bark",
      "suno/bark-small",
    ]
  }, {
    name: "preset",
    title: "Voice preset",
    type: "list",
    values: [
      "v2/en_speaker_0",
      "v2/en_speaker_1",
      "v2/en_speaker_2",
      "v2/en_speaker_3",
      "v2/en_speaker_4",
      "v2/en_speaker_5",
      "v2/en_speaker_6",
      "v2/en_speaker_7",
      "v2/en_speaker_8",
      "v2/en_speaker_9",
      "v2/zh_speaker_0",
      "v2/zh_speaker_1",
      "v2/zh_speaker_2",
      "v2/zh_speaker_3",
      "v2/zh_speaker_4",
      "v2/zh_speaker_5",
      "v2/zh_speaker_6",
      "v2/zh_speaker_7",
      "v2/zh_speaker_8",
      "v2/zh_speaker_9",
      "v2/fr_speaker_0",
      "v2/fr_speaker_1",
      "v2/fr_speaker_2",
      "v2/fr_speaker_3",
      "v2/fr_speaker_4",
      "v2/fr_speaker_5",
      "v2/fr_speaker_6",
      "v2/fr_speaker_7",
      "v2/fr_speaker_8",
      "v2/fr_speaker_9",
      "v2/de_speaker_0",
      "v2/de_speaker_1",
      "v2/de_speaker_2",
      "v2/de_speaker_3",
      "v2/de_speaker_4",
      "v2/de_speaker_5",
      "v2/de_speaker_6",
      "v2/de_speaker_7",
      "v2/de_speaker_8",
      "v2/de_speaker_9",
      "v2/hi_speaker_0",
      "v2/hi_speaker_1",
      "v2/hi_speaker_2",
      "v2/hi_speaker_3",
      "v2/hi_speaker_4",
      "v2/hi_speaker_5",
      "v2/hi_speaker_6",
      "v2/hi_speaker_7",
      "v2/hi_speaker_8",
      "v2/hi_speaker_9",
      "v2/it_speaker_0",
      "v2/it_speaker_1",
      "v2/it_speaker_2",
      "v2/it_speaker_3",
      "v2/it_speaker_4",
      "v2/it_speaker_5",
      "v2/it_speaker_6",
      "v2/it_speaker_7",
      "v2/it_speaker_8",
      "v2/it_speaker_9",
      "v2/ja_speaker_0",
      "v2/ja_speaker_1",
      "v2/ja_speaker_2",
      "v2/ja_speaker_3",
      "v2/ja_speaker_4",
      "v2/ja_speaker_5",
      "v2/ja_speaker_6",
      "v2/ja_speaker_7",
      "v2/ja_speaker_8",
      "v2/ja_speaker_9",
      "v2/ko_speaker_0",
      "v2/ko_speaker_1",
      "v2/ko_speaker_2",
      "v2/ko_speaker_3",
      "v2/ko_speaker_4",
      "v2/ko_speaker_5",
      "v2/ko_speaker_6",
      "v2/ko_speaker_7",
      "v2/ko_speaker_8",
      "v2/ko_speaker_9",
      "v2/pl_speaker_0",
      "v2/pl_speaker_1",
      "v2/pl_speaker_2",
      "v2/pl_speaker_3",
      "v2/pl_speaker_4",
      "v2/pl_speaker_5",
      "v2/pl_speaker_6",
      "v2/pl_speaker_7",
      "v2/pl_speaker_8",
      "v2/pl_speaker_9",
      "v2/pt_speaker_0",
      "v2/pt_speaker_1",
      "v2/pt_speaker_2",
      "v2/pt_speaker_3",
      "v2/pt_speaker_4",
      "v2/pt_speaker_5",
      "v2/pt_speaker_6",
      "v2/pt_speaker_7",
      "v2/pt_speaker_8",
      "v2/pt_speaker_9",
      "v2/ru_speaker_0",
      "v2/ru_speaker_1",
      "v2/ru_speaker_2",
      "v2/ru_speaker_3",
      "v2/ru_speaker_4",
      "v2/ru_speaker_5",
      "v2/ru_speaker_6",
      "v2/ru_speaker_7",
      "v2/ru_speaker_8",
      "v2/ru_speaker_9",
      "v2/es_speaker_0",
      "v2/es_speaker_1",
      "v2/es_speaker_2",
      "v2/es_speaker_3",
      "v2/es_speaker_4",
      "v2/es_speaker_5",
      "v2/es_speaker_6",
      "v2/es_speaker_7",
      "v2/es_speaker_8",
      "v2/es_speaker_9",
      "v2/tr_speaker_0",
      "v2/tr_speaker_1",
      "v2/tr_speaker_2",
      "v2/tr_speaker_3",
      "v2/tr_speaker_4",
      "v2/tr_speaker_5",
      "v2/tr_speaker_6",
      "v2/tr_speaker_7",
      "v2/tr_speaker_8",
      "v2/tr_speaker_9",
    ]
  }],

  data: {
    model: 'suno/bark',
    preset: 'v2/en_speaker_6',
  },

  transform: function (inputs: MecchiKV, state: MecchiKV): Promise<MecchiKV> {
    return new Promise(async resolve => {
      const payload = {
        ...state, ...{
          device: inputs.device,
          prompt: inputs.prompt
        }
      };

      const result: any = await ky.post('/mecchi/bark', {
        json: payload,
        timeout: false
      }).json();

      resolve({ samples: result.samples });
    });
  }
}

export default MecchiBarkNodeInfo;